# Generated by Django 2.1 on 2019-02-27 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 18, 19, 20, 552188), verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_idv',
            field=models.CharField(default='b0cf37e00de04af5a195a4f7e9b62d61', max_length=50, unique=True, verbose_name='用户唯一ID'),
        ),
    ]
